// One-time generator: us-atlas (US Census boundaries, lon/lat) projected with
// d3's Albers USA onto a 975x610 canvas -> src/ramen/usStates.js, plain SVG
// paths keyed by postal code. Run `node scripts/build-us-map.mjs` if us-atlas is updated.
// The output is committed so the widget has no map dependency at runtime.

import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { feature } from "topojson-client";
import { geoAlbersUsa, geoMercator, geoPath } from "d3-geo";

const require = createRequire(import.meta.url);
const MANITOBA_GEOJSON_URL =
  "https://services.arcgis.com/mMUesHYPkXjaFGfS/arcgis/rest/services/Manitoba_Provincial_Boundary/FeatureServer/0/query" +
  "?where=1%3D1" +
  "&outFields=*" +
  "&returnGeometry=true" +
  "&outSR=4326" +
  "&f=geojson";
const topology = JSON.parse(readFileSync(require.resolve("us-atlas/states-10m.json"), "utf8"));

const CODES = {
  Alabama: "AL", Alaska: "AK", Arizona: "AZ", Arkansas: "AR", California: "CA",
  Colorado: "CO", Connecticut: "CT", Delaware: "DE", "District of Columbia": "DC",
  Florida: "FL", Georgia: "GA", Hawaii: "HI", Idaho: "ID", Illinois: "IL",
  Indiana: "IN", Iowa: "IA", Kansas: "KS", Kentucky: "KY", Louisiana: "LA",
  Maine: "ME", Maryland: "MD", Massachusetts: "MA", Michigan: "MI", Minnesota: "MN",
  Mississippi: "MS", Missouri: "MO", Montana: "MT", Nebraska: "NE", Nevada: "NV",
  "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM", "New York": "NY",
  "North Carolina": "NC", "North Dakota": "ND", Ohio: "OH", Oklahoma: "OK",
  Oregon: "OR", Pennsylvania: "PA", "Rhode Island": "RI", "South Carolina": "SC",
  "South Dakota": "SD", Tennessee: "TN", Texas: "TX", Utah: "UT", Vermont: "VT",
  Virginia: "VA", Washington: "WA", "West Virginia": "WV", Wisconsin: "WI", Wyoming: "WY",
};

// d3's standard fit of the lower 48 + AK/HI insets into 975x610
const project = geoAlbersUsa()
  .scale(1050)
  .translate([487.5, 340]);
const projectManitoba = geoMercator()
  .scale(550)
  .translate([1418, 692]);

// A ring of lon/lat points -> "M x y L x y ... Z" in whole pixels: at this size
// sub-pixel precision only costs bytes. Points outside the projection (none for
// states) are dropped.
const ring = (pts) => {
  const xy = pts.map(project).filter(Boolean);
  return xy.map(([x, y], i) => `${i ? "L" : "M"}${Math.round(x)} ${Math.round(y)}`).join("") + "Z";
};
const polygon = (rings) => rings.map(ring).join("");

const states = {};
for (const f of feature(topology, topology.objects.states).features) {
  const code = CODES[f.properties.name];
  if (!code) continue;   // territories are not in CODES
  const g = f.geometry;
  const d = g.type === "Polygon" ? polygon(g.coordinates) : g.coordinates.map(polygon).join("");
  states[code] = { name: f.properties.name, d };
}

console.log("Fetching Manitoba boundary...");

const response = await fetch(MANITOBA_GEOJSON_URL);

if (!response.ok) {
  throw new Error(
    `Failed to fetch Manitoba boundary: ${response.status} ${response.statusText}`,
  );
}

const manitobaGeoJSON = await response.json();
const manitobaFeature = manitobaGeoJSON.features?.[0];

if (!manitobaFeature) {
  throw new Error("Manitoba GeoJSON did not contain a feature");
}

const manitobaPath = geoPath(projectManitoba)(manitobaFeature);

if (!manitobaPath || manitobaPath.includes("NaN")) {
  throw new Error(
    `Generated invalid Manitoba SVG path: ${manitobaPath?.slice(0, 200)}`,
  );
}

const out = `// Generated by scripts/build-us-map.mjs from us-atlas
// and the Manitoba provincial boundary dataset.
// Do not edit by hand. viewBox 0 0 975 610.
export const VIEW_BOX = "0 0 975 610";
export const US_STATES = ${JSON.stringify(states)};
export const MANITOBA = ${JSON.stringify({
  name: "Manitoba",
  d: manitobaPath,
})};
`;
writeFileSync(new URL("../src/ramen/usStates.js", import.meta.url), out);
console.log(
  `wrote ${Object.keys(states).length} states + Manitoba, ${(out.length / 1024).toFixed(0)} KB`,
);