// One-time generator: us-atlas (US Census boundaries, lon/lat) projected with
// d3's Albers USA onto a 975x610 canvas -> src/copilot/usStates.js, plain SVG
// paths keyed by postal code. Run `node scripts/build-us-map.mjs` if us-atlas is updated.
// The output is committed so the widget has no map dependency at runtime.

import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { feature } from "topojson-client";
import { geoAlbersUsa } from "d3-geo";

const require = createRequire(import.meta.url);
const topology = JSON.parse(readFileSync(require.resolve("us-atlas/states-10m.json"), "utf8"));

const CODES = {
  Alabama: "AL", Alaska: "AK", Arizona: "AZ", Arkansas: "AR", California: "CA",
  Colorado: "CO", Connecticut: "CT", Delaware: "DE", "District of Columbia": "DC",
  Florida: "FL", Georgia: "GA", Hawaii: "HI", Idaho: "ID", Illinois: "IL",
  Indiana: "IN", Iowa: "IA", Kansas: "KS", Kentucky: "KY", Louisiana: "LA",
  Maine: "ME", Maryland: "MD", Massachusetts: "MA", Michigan: "MI", Minnesota: "MN",
  Mississippi: "MS", Missouri: "MO", Montana: "MT", Nebraska: "NE", Nevada: "NV",
  "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM", "New York": "NY",
  "North Carolina": "NC", "North Dakota": "ND", Ohio: "OH", Oklahoma: "OK",
  Oregon: "OR", Pennsylvania: "PA", "Rhode Island": "RI", "South Carolina": "SC",
  "South Dakota": "SD", Tennessee: "TN", Texas: "TX", Utah: "UT", Vermont: "VT",
  Virginia: "VA", Washington: "WA", "West Virginia": "WV", Wisconsin: "WI", Wyoming: "WY",
};

// d3's standard fit of the lower 48 + AK/HI insets into 975x610
const project = geoAlbersUsa().scale(1300).translate([487.5, 305]);

// A ring of lon/lat points -> "M x y L x y ... Z" in whole pixels: at this size
// sub-pixel precision only costs bytes. Points outside the projection (none for
// states) are dropped.
const ring = (pts) => {
  const xy = pts.map(project).filter(Boolean);
  return xy.map(([x, y], i) => `${i ? "L" : "M"}${Math.round(x)} ${Math.round(y)}`).join("") + "Z";
};
const polygon = (rings) => rings.map(ring).join("");

const states = {};
for (const f of feature(topology, topology.objects.states).features) {
  const code = CODES[f.properties.name];
  if (!code) continue;   // territories are not in CODES
  const g = f.geometry;
  const d = g.type === "Polygon" ? polygon(g.coordinates) : g.coordinates.map(polygon).join("");
  states[code] = { name: f.properties.name, d };
}

const out = `// Generated by scripts/build-us-map.mjs from us-atlas (US Census, public domain).
// Do not edit by hand. viewBox 0 0 975 610.
export const VIEW_BOX = "0 0 975 610";
export const US_STATES = ${JSON.stringify(states)};
`;
writeFileSync(new URL("../src/copilot/usStates.js", import.meta.url), out);
console.log(`wrote ${Object.keys(states).length} states, ${(out.length / 1024).toFixed(0)} KB`);
